from .agent_A import search_queries_reccomendation_agent, search_queries_recommendation_task
from .agent_B import search_engine_agent, search_engine_task
from .agent_C import scraping_agent,scraping_task
from .agent_D import procurement_report_author_agent, procurement_report_author_task